export const INVENTORY = [
    {
        "name": 'Wallet',
        "titals":"Hidelink Men Formal Brown Genuine Leather Wallet (9 Card Slots)",
        "price": 499,
        "quantity": 0,
        "img":"./assets/img/product1.jpeg",
        "figcaption":'Men Formal Wallet',
        "Color":'Brown',
        "size" : 'XS',
        "rating" : 3,
        "description" : "Crafted from genuine leather, this Hidelink wallet not only has a classy finish, but also has stitch detailing to add to its overall look",
        "Specifications":"Comfortable to wear all day long. Make your daughter special for every one Wash Care Instructions: Wash In Cold Water. Do Not Bleach",
        "selected": false,
        "deincre1":true,
        "status" :"Add from Cart",
        "bgcolor":"#3f51b5",
        "totalquantity":0
      },
      {
        "name": 'Girls Dress',
        "titals":"Aarika Baby Girls' A-Line Knee-Long Dress",
        "price": 900,
        "quantity": 0,
        "img":'./assets/img/girl_dress.jpeg',
        "figcaption":'Girls Dress',
        "Color":'Blue, Sleeveless',
        "size" : 'XS',
        "rating" : 4,
        "description" : "Fabric: Cotton and Polyester.Suitable for : Girl's Ideal for all party occasions, birthday, festivals and gifting.",
        "Specifications":"Go Cashless: Get 10% cashback up to Rs. 50 using BHIM UPI (available only on mobile app/website) or RuPay cards. Offer period 1st September to 30th September. Cashback will be credited as Amazon Pay balance within 15 days from purchase. Here's how (terms and conditions apply)",
        "selected": false,
        "deincre1":true,
        "status" :"Add from Cart",
        "bgcolor":' #3f51b5',
        "totalquantity":0
      },
      {
        "name": 'Baby Dress',
        "titals":"Baby Blossom Boys Party(Festive) Dress T-shirt (Red)",
        "price": 530,
        "quantity": 0,
        "img":'./assets/img/boys_dress.jpeg',
        "figcaption":'Baby Dress',
        "Color":'Red',
        "size" : 'XS',
        "rating" : 5,
        "description" : "Brand:- Baby Blossom, Primary Product Type: Dress, Secondary Product Type: T-shirt",
        "Specifications":"Comfortable to wear all day long. Make your daughter special for every one Wash Care Instructions: Wash In Cold Water. Do Not Bleach",
        "selected": false,
        "deincre1":true,
        "status" :"Add from Cart",
        "bgcolor":' #3f51b5',
        "totalquantity":0
      }
];